spring.application.name=api-kazukiTurismo
spring.datasource.url=jdbc:mysql://localhost:3306/kazuki_turismo
spring.datasource.username=root
spring.datasource.password=Kazuki_Turismo.
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver