server.port=8080
server.servlet.context-path=/api-kazukiTurismo
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Configuración de la Base de Datos para JPA 
spring.datasource.url=jdbc:mysql://localhost:3306/kazuki_turismo_sch
spring.datasource.username=root
spring.datasource.password=-Jul?43018
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de Hibernate / JPA
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
# Aquí se crean las tablas si no existen o las actualiza y la seg línea muestra las consultas SQL en la consola
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true